server:
  port: '8084'
spring:
  security:
    oauth2:
      client:
        registration:
          test:
            client-name: Spring Boot Auth Server
            authorization-grant-type: client_credentials
            client-id: localhost
            provider: test
            client-secret: localhost
        provider:
          test:
            token-uri: http://localhost:64200/oauth2/token
oauth2:
  registration:
    id: test
resource:
  base: http://localhost:64203
  path: /test
